"""shared/hw_mapping.py — stable HAT identity layer for AstromechOS.

Reads `<role>/config/config_mapping.json` and exposes a clean API for
binding STABLE HAT IDENTITIES (e.g. ``Body_HAT_A``) to:
  - the current I2C address (changes when the operator re-jumpers)
  - the channel count per HAT
  - the legacy flat-name alias (``Servo_S0..S15`` etc.) so existing
    .chor / shortcuts / arms cfg keep working with zero migration.

Chantier 2026-05-28 G: labels + calibrations in dome_angles.json /
servo_angles.json move from being keyed by ``Servo_M0`` (which shifts
when the cfg order changes) to being anchored to the HAT IDENTITY —
so re-jumpering 0x41→0x42 just updates ``address`` in the mapping
and every label/open/close/speed value follows automatically.

This module is the READ side only. It never writes config_mapping.json;
that's the job of scripts/detect_hats.py + the Settings UI. The driver
+ servo_bp + calibration panel all import this helper to translate
between {flat external name} ↔ {HAT identity, channel} ↔ {I2C addr}.

Public API
----------
load_for(role)                    → Optional[dict]  parsed JSON or None.
synthesize_from_layout(role)      → dict  fallback when no mapping yet.
all_hats(mapping)                 → list[dict]      sorted by alias_base.
hat_by_id(mapping, id)            → Optional[dict]
hat_by_address(mapping, addr)     → Optional[dict]
channels_for(mapping, id)         → int
flat_name(mapping, id, ch)        → Optional[str]   'Servo_S3' from (Body_HAT_A,3).
identity_for(mapping, flat)       → Optional[(str,int)]  reverse of flat_name.
"""
from __future__ import annotations

import configparser
import json
import logging
import re
from pathlib import Path
from typing import Any, Optional

log = logging.getLogger('hw_mapping')

# Resolved at import time; tests override via H._REPO = Path(...).
_REPO = Path(__file__).resolve().parent.parent

SCHEMA_VERSION = 1

# Validators
_ID_RE   = re.compile(r'^[A-Z][A-Za-z0-9]+_HAT_[A-Z]$')
# Accept both '0x40' and '0X40' (case-insensitive prefix) so JSON
# generated by hand-edits / migration scripts is forgiving. We
# normalise to lowercase '0xNN' on output.
_ADDR_RE = re.compile(r'^0[xX][0-9a-fA-F]{2}$')
_ALIAS_PREFIX_RE = re.compile(r'^Servo_[A-Z]$')

# Role taxonomy — keep in lock-step with shared/hw_layout.py role tags.
ROLES = ('servo_dome', 'servo_body', 'motor_drive')


def _path_for(role: str) -> Path:
    sub = 'slave' if role == 'slave' else 'master'
    return _REPO / sub / 'config' / 'config_mapping.json'


def load_for(role: str) -> Optional[dict]:
    """Load config_mapping.json for <role>. Returns None on any error
    (file absent, malformed JSON, missing 'hats' list). Callers fall
    back to `synthesize_from_layout(role)` for the legacy path."""
    p = _path_for(role)
    if not p.is_file():
        log.info("hw_mapping: %s absent — caller should synthesize", p)
        return None
    try:
        with p.open('r', encoding='utf-8') as f:
            data = json.load(f)
    except (OSError, ValueError) as e:
        log.warning("hw_mapping: %s unreadable (%s) — ignoring", p, e)
        return None
    if not isinstance(data, dict) or not isinstance(data.get('hats'), list):
        log.warning("hw_mapping: %s missing 'hats' list — ignoring", p)
        return None
    return data


def _normalise_addr(raw: Any) -> Optional[str]:
    """Return '0xNN' (lowercase) or None on invalid."""
    if isinstance(raw, int):
        if 0x40 <= raw <= 0x77:
            return f'0x{raw:02x}'
        return None
    if not isinstance(raw, str):
        return None
    s = raw.strip()
    if not _ADDR_RE.match(s):
        return None
    n = int(s, 16)
    if not (0x40 <= n <= 0x77):
        return None
    return f'0x{n:02x}'


def _valid_hat(h: Any) -> bool:
    """Defensive validator for one hats[] entry."""
    if not isinstance(h, dict):
        return False
    if not isinstance(h.get('id'), str) or not _ID_RE.match(h['id']):
        return False
    if h.get('role') not in ROLES:
        return False
    if _normalise_addr(h.get('address')) is None:
        return False
    ch = h.get('channels')
    if not isinstance(ch, int) or ch <= 0 or ch > 32:
        return False
    # alias_prefix is optional (None for motor HAT); validate when present.
    ap = h.get('alias_prefix')
    if ap is not None:
        if not isinstance(ap, str) or not _ALIAS_PREFIX_RE.match(ap):
            return False
        ab = h.get('alias_base')
        if not isinstance(ab, int) or ab < 0:
            return False
    return True


def all_hats(mapping: Optional[dict]) -> list[dict]:
    """Return the valid hats list sorted by (alias_base, id) for stable
    iteration. Malformed entries silently dropped (logged at debug)."""
    if not mapping:
        return []
    out = []
    for h in mapping.get('hats') or []:
        if _valid_hat(h):
            out.append(h)
        else:
            log.debug("hw_mapping: dropped malformed hat entry %r", h)
    # alias_base may be None (motor HAT) — push those to end.
    out.sort(key=lambda h: (h.get('alias_base') if h.get('alias_base') is not None
                             else 1 << 30, h['id']))
    return out


def hat_by_id(mapping: Optional[dict], identity: str) -> Optional[dict]:
    for h in all_hats(mapping):
        if h['id'] == identity:
            return h
    return None


def hat_by_address(mapping: Optional[dict], addr: Any) -> Optional[dict]:
    norm = _normalise_addr(addr)
    if norm is None:
        return None
    for h in all_hats(mapping):
        if h['address'].lower() == norm:
            return h
    return None


def channels_for(mapping: Optional[dict], identity: str) -> int:
    h = hat_by_id(mapping, identity)
    return int(h['channels']) if h else 0


def flat_name(mapping: Optional[dict], identity: str, ch: int) -> Optional[str]:
    """Return the backwards-compat external name (e.g. 'Servo_S3') for
    a (HAT identity, channel) pair. Returns None when the HAT has no
    alias_prefix (e.g. motor HAT) or the channel is out of range."""
    h = hat_by_id(mapping, identity)
    if h is None:
        return None
    if h.get('alias_prefix') is None:
        return None
    if not (0 <= ch < h['channels']):
        return None
    return f"{h['alias_prefix']}{int(h['alias_base']) + ch}"


def identity_for(mapping: Optional[dict], flat: str) -> Optional[tuple]:
    """Reverse of flat_name. Returns (identity, channel) for a name like
    'Servo_S3' by scanning the mapping. Useful for .chor file load
    compatibility — the chor still says ``Servo_S0`` and the driver
    routes it to ``(Body_HAT_A, 0)`` regardless of which I2C addr that
    HAT currently lives at."""
    if not isinstance(flat, str):
        return None
    for h in all_hats(mapping):
        prefix = h.get('alias_prefix')
        if not prefix or not flat.startswith(prefix):
            continue
        suffix = flat[len(prefix):]
        if not suffix.isdigit():
            continue
        n = int(suffix)
        base = int(h.get('alias_base') or 0)
        if base <= n < base + h['channels']:
            return (h['id'], n - base)
    return None


# ─────────────────────────────────────────────────────────────────────
# Synthesis fallback — used by drivers when config_mapping.json is
# absent (first boot of new code, or before the operator has run
# detect_hats). Reads the legacy cfg [i2c_servo_hats] section and
# produces an equivalent mapping in memory. Phase G2 wires this in
# at the driver setup() so existing installs keep working without
# any operator action.
# ─────────────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────
# Calibration JSON format helpers (Phase G3 chantier 2026-05-28)
# ─────────────────────────────────────────────────────────────────────
# Two formats coexist on disk during the migration window:
#   FLAT (legacy):  {"Servo_M0": {"label":..,"open":..,"close":..,"speed":..}, ...}
#   NESTED (new):   {"Dome_HAT_A": {"0": {"label":..,...}, "1": {...}, ...}, ...}
# The new format anchors data to the HAT IDENTITY so re-jumpering an
# I2C address leaves every label / open / close / speed value intact.
# Driver reads NESTED first, falls back to FLAT for legacy files,
# writes NESTED only (migration-on-save).

def is_nested_format(d: Any) -> bool:
    """True iff `d` looks like the new nested-by-identity calibration.
    Heuristic: at least one top-level key matches _ID_RE and its value
    is a dict whose keys are numeric strings (channel indices)."""
    if not isinstance(d, dict) or not d:
        return False
    for k, v in d.items():
        if not isinstance(k, str) or not _ID_RE.match(k):
            continue
        if not isinstance(v, dict):
            continue
        # First channel-keyed sub-entry confirms nested format.
        for ch_key, ch_val in v.items():
            if isinstance(ch_key, str) and ch_key.isdigit() and isinstance(ch_val, dict):
                return True
    return False


def flat_calibration_to_nested(flat: dict, mapping: Optional[dict]) -> dict:
    """Convert legacy flat calibration ({"Servo_S0": {...}}) to nested
    by HAT identity ({"Body_HAT_A": {"0": {...}}}).

    Entries whose flat name can't be resolved by the mapping are
    DROPPED (logged at debug). This is intentional — a stale entry from
    a HAT that no longer exists shouldn't pollute the new file.
    Callers can pass synthesize_from_layout() output if config_mapping
    isn't on disk yet."""
    out: dict[str, dict] = {}
    if not isinstance(flat, dict):
        return out
    for name, entry in flat.items():
        if not isinstance(entry, dict):
            continue
        # Skip already-nested entries (defensive — caller may pass mixed).
        if isinstance(name, str) and _ID_RE.match(name):
            out.setdefault(name, {}).update(
                {k: v for k, v in entry.items()
                 if isinstance(k, str) and k.isdigit()}
            )
            continue
        pair = identity_for(mapping, name)
        if pair is None:
            log.debug("flat_calibration_to_nested: dropping unmapped %r", name)
            continue
        identity, ch = pair
        out.setdefault(identity, {})[str(ch)] = dict(entry)
    return out


def nested_calibration_to_flat(nested: dict, mapping: Optional[dict]) -> dict:
    """Inverse of flat_calibration_to_nested — used by servo_bp GET
    endpoints that still return flat names to the UI / API for
    backwards compatibility. Unmappable entries (HATs not present in
    mapping) are silently skipped."""
    out: dict[str, dict] = {}
    if not isinstance(nested, dict):
        return out
    for identity, channels in nested.items():
        if not isinstance(channels, dict):
            continue
        for ch_key, entry in channels.items():
            if not (isinstance(ch_key, str) and ch_key.isdigit()
                    and isinstance(entry, dict)):
                continue
            flat = flat_name(mapping, identity, int(ch_key))
            if flat is None:
                continue
            out[flat] = dict(entry)
    return out


def normalise_calibration(raw: Any, mapping: Optional[dict]) -> dict:
    """Return raw as NESTED format regardless of input shape.

    Accepts FLAT (legacy), NESTED (new), or empty/None. Used by every
    consumer (driver + servo_bp) so each one reads ONE format
    internally without worrying which was on disk."""
    if not isinstance(raw, dict) or not raw:
        return {}
    if is_nested_format(raw):
        return raw
    return flat_calibration_to_nested(raw, mapping)


def synthesize_from_layout(role: str,
                           cfg_paths: Optional[list[str]] = None
                           ) -> dict:
    """Best-effort synthesis from the legacy cfg.

    For 'master': reads [i2c_servo_hats] master_hats (comma-sep addrs);
    each becomes Dome_HAT_A, Dome_HAT_B, ... with alias_base = idx*16.

    For 'slave': reads slave_motor_hat (single addr, Motor_HAT_A) +
    slave_hats (comma-sep, Body_HAT_A, B, ...). Motor HAT has no alias.

    Used as the in-memory fallback when config_mapping.json doesn't
    exist yet. The actual on-disk file is written by Phase G2's
    one-shot migrator or by the Settings UI."""
    cfg = configparser.ConfigParser()
    if cfg_paths:
        cfg.read(cfg_paths)
    hats: list[dict] = []

    def _parse_addrs(raw: str) -> list[str]:
        out = []
        for tok in (raw or '').split(','):
            n = _normalise_addr(tok.strip())
            if n is not None and n not in out:
                out.append(n)
        return out

    if role == 'master':
        addrs = _parse_addrs(cfg.get('i2c_servo_hats', 'master_hats',
                                     fallback='0x40'))
        for i, a in enumerate(addrs):
            hats.append({
                'id':           f"Dome_HAT_{chr(ord('A')+i)}",
                'role':         'servo_dome',
                'address':      a,
                'channels':     16,
                'alias_prefix': 'Servo_M',
                'alias_base':   i * 16,
            })
    else:
        motor = _normalise_addr(cfg.get('i2c_servo_hats', 'slave_motor_hat',
                                        fallback='0x40'))
        if motor:
            hats.append({
                'id':           'Motor_HAT_A',
                'role':         'motor_drive',
                'address':      motor,
                'channels':     16,
                'alias_prefix': None,
                'alias_base':   None,
            })
        addrs = _parse_addrs(cfg.get('i2c_servo_hats', 'slave_hats',
                                     fallback='0x41'))
        for i, a in enumerate(addrs):
            hats.append({
                'id':           f"Body_HAT_{chr(ord('A')+i)}",
                'role':         'servo_body',
                'address':      a,
                'channels':     16,
                'alias_prefix': 'Servo_S',
                'alias_base':   i * 16,
            })

    return {
        'schema_version': SCHEMA_VERSION,
        'host':           role,
        'updated_at':     None,
        'synthesised':    True,   # caller can persist if desired
        'hats':           hats,
    }
